(()=>{'use strict';const E=PriceEngine,P=PricePublisher,$=id=>document.getElementById(id);let api=new P.GitHub(),snapshot=null,review=null,busy=false,connected=false;
const selected=()=>review?review.rows.filter(r=>r.status==='change'&&$('row-'+r.id)?.checked):[];
function status(message,error=false){$('status').textContent=message;$('status').classList.toggle('error',error);}
function readiness(){const rows=selected(),large=rows.some(r=>r.largeChange);$('large-confirm-wrap').hidden=!large;$('selection-count').textContent=rows.length?'Выбрано: '+rows.length:'';$('publish').disabled=busy||!rows.length||!$('confirm').checked||(large&&!$('large-confirm').checked);}
function setBusy(value){busy=value;document.querySelectorAll('button,input,textarea').forEach(el=>el.disabled=value);if(!value){$('preorder-markup').disabled=!$('preorders').checked;document.querySelectorAll('[data-unchanged]').forEach(el=>el.disabled=true);}readiness();}
function invalidate(){review=null;$('review').hidden=true;$('confirm').checked=false;$('large-confirm').checked=false;$('success').hidden=true;readiness();}
function rowCell(tr,text,cls){const td=document.createElement('td');td.textContent=text;if(cls)td.className=cls;tr.append(td);return td;}
function render(){const rows=review.rows.filter(r=>r.status==='change'||r.status==='same');$('rows').replaceChildren();for(const r of rows){const tr=document.createElement('tr'),td=document.createElement('td'),check=document.createElement('input');check.type='checkbox';check.id='row-'+r.id;check.checked=r.status==='change';check.disabled=r.status==='same';if(check.disabled)check.dataset.unchanged='true';check.setAttribute('aria-label','Обновить '+r.name);check.addEventListener('change',()=>{$('confirm').checked=false;$('large-confirm').checked=false;readiness();});td.append(check);tr.append(td);const name=rowCell(tr,r.name);if(r.largeChange){const note=document.createElement('small');note.textContent='Изменение больше 20%';name.append(note);}rowCell(tr,E.money(r.supplierPrice));rowCell(tr,E.money(r.oldPrice));rowCell(tr,E.money(r.price),'price-new');rowCell(tr,r.status==='same'?'Без изменений':(r.price>r.oldPrice?'+':'−')+E.money(Math.abs(r.price-r.oldPrice)));$('rows').append(tr);}
const errors=[...review.issues,...review.rows.filter(r=>r.status==='error'||r.status==='protected')];$('issues').replaceChildren();for(const e of errors){const li=document.createElement('li');li.textContent='Строка '+e.line+': '+e.text+' — '+e.reason;$('issues').append(li);}$('issues-title').textContent='Не публикуются: '+errors.length+' строк';$('issues-box').hidden=!errors.length;$('issues-box').open=errors.length>0;$('summary').textContent='Изменений: '+review.rows.filter(r=>r.status==='change').length+' · Без изменений: '+review.rows.filter(r=>r.status==='same').length;$('coverage').textContent='Других вариантов в каталоге: '+review.untouched+'. Они сохранятся. Служебных строк пропущено: '+review.ignored.length+'.';$('large-note').hidden=!rows.some(r=>r.largeChange);$('confirm').checked=false;$('large-confirm').checked=false;$('review').hidden=false;readiness();}
$('source').addEventListener('input',invalidate);$('markup').addEventListener('input',invalidate);$('preorder-markup').addEventListener('input',invalidate);$('preorders').addEventListener('change',()=>{$('preorder-markup').disabled=!$('preorders').checked;invalidate();});
$('example').onclick=()=>{$('source').value='▪️ Apple\nAirPods 4 - 10.500\nAirPods Pro 3 - 17.600\n\n▪️ iPhone 17 Pro\n17 Pro 256GB Blue 🇯🇵 - 98.500\n\n▪️ iPhone 18 Pro\n18 pro 256 black esim 135000';invalidate();status('Это пример для проверки интерфейса. Замените его актуальным прайсом перед публикацией.');};
$('connect').onclick=async()=>{const token=$('token').value.trim();if(!token){status('Вставьте ключ в поле доступа.',true);return;}setBusy(true);status('Проверяю доступ…');try{const next=new P.GitHub(token);await next.head();api=next;connected=true;snapshot=null;invalidate();$('token').value='';$('access-state').textContent='подключён';status('Ключ принят. Теперь проверьте прайс.');}catch(e){status(e.message,true);}finally{setBusy(false);}};
$('forget').onclick=()=>{api=new P.GitHub();connected=false;$('token').value='';$('access-state').textContent='не подключён';status('Ключ удалён из памяти вкладки.');};
$('price-form').onsubmit=async event=>{event.preventDefault();if(busy)return;const text=$('source').value;if(!text.trim()){status('Вставьте прайс.',true);return;}if(text.length>150000){status('Прайс слишком большой. Вставьте до 150 000 символов за один раз.',true);return;}const settings={markup:$('markup').value,includePreorders:$('preorders').checked,preorderMarkup:$('preorder-markup').value};invalidate();setBusy(true);status('Загружаю актуальный каталог…');try{if(!snapshot||await api.head()!==snapshot.sha)snapshot=await api.snapshot();review=E.preview(text,snapshot.products,settings);render();status('Расчёт готов. Проверьте выбранные строки.');$('review').scrollIntoView({behavior:'smooth',block:'start'});}catch(e){status(e.message,true);}finally{setBusy(false);}};
$('confirm').onchange=readiness;$('large-confirm').onchange=readiness;$('select-all').onclick=()=>{document.querySelectorAll('#rows input:not([data-unchanged])').forEach(x=>x.checked=true);$('confirm').checked=false;$('large-confirm').checked=false;readiness();};$('select-none').onclick=()=>{document.querySelectorAll('#rows input').forEach(x=>x.checked=false);$('confirm').checked=false;readiness();};
async function verifyLive(changes){for(let i=0;i<24;i++){await new Promise(r=>setTimeout(r,5000));try{const response=await fetch('/catalog/?price-check='+Date.now(),{cache:'no-store',credentials:'omit'});if(!response.ok)continue;const data=P.readProducts(await response.text());if(changes.every(x=>data.some(p=>p.id===x.id&&p.price===x.price))){$('deploy-status').textContent='Готово — новые цены уже на сайте.';return;}}catch{}}$('deploy-status').textContent='Изменения сохранены, но появление на сайте пока не подтверждено. Проверьте каталог немного позже.';}
$('publish').onclick=async()=>{if(busy||$('publish').disabled)return;if(!connected){$('access-details').open=true;$('token').focus();status('Для публикации подключите ключ доступа выше. После подключения потребуется повторная проверка прайса.',true);return;}const changes=selected().map(({id,oldPrice,price})=>({id,oldPrice,price}));setBusy(true);status('Публикую выбранные цены…');try{const files=P.buildFiles(snapshot,changes),result=await api.publish(snapshot,files);review=null;snapshot=null;$('review').hidden=true;$('success').hidden=false;$('commit-link').href='https://github.com/crazytor44-bot/applemarket26/commit/'+result.sha;$('deploy-status').textContent='Цены сохранены. Ожидаем публикации сайта…';status('Отправлено '+changes.length+' изменений.');void verifyLive(changes);}catch(e){status(e.message,true);$('confirm').checked=false;$('large-confirm').checked=false;}finally{setBusy(false);}};
window.addEventListener('pagehide',()=>{api.token='';$('token').value='';connected=false;$('access-state').textContent='не подключён';});readiness();
})();
