/* Pure parsing and matching; supplier text never leaves the browser. */
(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory();else root.PriceEngine=factory();})(typeof globalThis!=='undefined'?globalThis:this,()=>{
'use strict';
const money=n=>new Intl.NumberFormat('ru-RU').format(n)+' ₽';
function key(s){return String(s).normalize('NFKC').toLowerCase().replace(/\([^)]*(?:rustore|гаранти)[^)]*\)/g,'').replace(/🇯🇵/g,' jp ').replace(/🇮🇳/g,' in ').replace(/🇪🇺/g,' eu ').replace(/🇨🇳/g,' cn ').replace(/🇺🇸/g,' us ').replace(/apple\s*watch/g,' ').replace(/\bapple\b|\biphone\b/g,' ').replace(/\bse\s*([23])\b/g,'se$1').replace(/\bs\s*11\b/g,'series 11').replace(/\b(\d+)\s*(?:tb|тб)\b/g,(_,n)=>' '+Number(n)*1024+'gb ').replace(/\b(\d+)\s*(?:gb|гб)\b/g,' $1gb ').replace(/\b(128|256|512|1024|2048)\b(?!\s*gb)/g,'$1gb').replace(/\b1\s*sim\b/g,'1sim').replace(/\be\s*sim\b/g,'esim').replace(/usb[\s‑–—-]*c/g,'usbc').replace(/[^\p{L}\p{N}/]+/gu,' ').trim().replace(/\s+/g,' ');}
function parse(text){const entries=[],issues=[],ignored=[];const lines=String(text).replace(/\r/g,'').replace(/([0-9₽🔥❗])[ \t]+(?=(?:iphone[ \t]+)?18[ \t]+pro\b)/gi,'$1\n').split('\n');
lines.forEach((raw,index)=>{const line=raw.trim();if(!line)return;const number=index+1;
if(/^[▪▫◾]/u.test(line)||/^iCenter\s+Stavropol\s*,?\s*\[/i.test(line)||/^От\s+\d+\s*шт/i.test(line)||/^🇯🇵\s*\(eSIM\)|^🇮🇳\s*\(SIM|^🇪🇺\s*\(SIM/i.test(line)){ignored.push({line:number,text:line});return;}
const clean=line.replace(/\*.*$/,'').replace(/[🚛🚚🔥❗❕‼️]/gu,'').trim();
const m=clean.match(/^(.*?)\s+(?:[-–—:]\s*)?(\d{1,3}(?:[. \u00a0\u202f]\d{3})+|\d{4,7})\s*(?:₽|руб\.?|р\.)?$/i);
if(!m||!m[1].trim()){issues.push({line:number,text:line,reason:'Не распознана цена. Пример: AirPods 4 - 10.000'});return;}
const amount=Number(m[2].replace(/[. \u00a0\u202f]/g,''));if(!Number.isSafeInteger(amount)||amount<=0||amount>2000000){issues.push({line:number,text:line,reason:'Цена вне допустимого диапазона'});return;}
entries.push({line:number,text:line,name:m[1].trim(),key:key(m[1]),supplierPrice:amount});});return {entries,issues,ignored};}
function preview(text,products,settings){const markup=Number(settings.markup),preorderMarkup=Number(settings.preorderMarkup);if(!Number.isSafeInteger(markup)||markup<0||markup>100000)throw Error('Наценка должна быть целым числом от 0 до 100 000 ₽');if(settings.includePreorders&&(!Number.isSafeInteger(preorderMarkup)||preorderMarkup<0||preorderMarkup>100000))throw Error('Проверьте наценку предзаказов');
const parsed=parse(text),byKey=new Map(),counts=new Map();for(const p of products){const k=key(p.name);if(!byKey.has(k))byKey.set(k,[]);byKey.get(k).push(p);}for(const e of parsed.entries)counts.set(e.key,(counts.get(e.key)||0)+1);
const rows=parsed.entries.map(e=>{const candidates=byKey.get(e.key)||[];let reason='';if(counts.get(e.key)>1)reason='Повтор в прайсе: оставьте одну строку этого варианта';else if(candidates.length!==1)reason=candidates.length?'Несколько совпадений — нужно уточнить вариант':'Нет точного совпадения в каталоге';const p=candidates.length===1?candidates[0]:null;if(!reason&&p.preorder&&!settings.includePreorders)reason='Предзаказ защищён от обычного обновления';if(reason)return {...e,id:p?.id,status:p?.preorder&&!settings.includePreorders&&counts.get(e.key)===1?'protected':'error',reason};const price=e.supplierPrice+(p.preorder?preorderMarkup:markup);if(price>2000000)return {...e,status:'error',reason:'Итоговая цена слишком велика'};return {...e,id:p.id,name:p.name,oldPrice:p.price,price,preorder:!!p.preorder,status:price===p.price?'same':'change',largeChange:Math.abs(price-p.price)/p.price>.2};});
return {...parsed,rows,untouched:products.length-new Set(rows.filter(x=>x.status==='change'||x.status==='same').map(x=>x.id)).size};}
function orderUrl(p,price){if(!/^https:\/\/wa\.me\//.test(p.url||''))return p.url;const u=new URL(p.url),text=u.searchParams.get('text');if(!text)throw Error('Не найден текст заказа для '+p.name);const replaced=text.replace(/(за\s+)[\d\s\u00a0\u202f.,]+\s*₽/,(_,prefix)=>prefix+money(price));if(replaced===text&&price!==p.price)throw Error('Не удалось обновить цену сообщения для '+p.name);u.searchParams.set('text',replaced);return u.toString();}
function updateProducts(products,changes){const map=new Map();for(const x of changes){if(map.has(x.id))throw Error('Повтор выбранного товара');if(!Number.isSafeInteger(x.price)||x.price<=0||x.price>2000000)throw Error('Недопустимая цена');map.set(x.id,x);}for(const id of map.keys())if(!products.some(p=>p.id===id))throw Error('Товар исчез из каталога');return products.map(p=>{const x=map.get(p.id);if(!x)return {...p};if(p.price!==x.oldPrice)throw Error('Цена уже изменилась: '+p.name+'. Выполните проверку заново.');return {...p,price:x.price,url:orderUrl(p,x.price)};});}
return {money,key,parse,preview,orderUrl,updateProducts};
});
