(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory(require('./engine.js'));else root.PricePublisher=factory(root.PriceEngine);})(typeof globalThis!=='undefined'?globalThis:this,E=>{
'use strict';const REPO='crazytor44-bot/applemarket26';
function htmlDoc(s){return new DOMParser().parseFromString(s,'text/html');}
function readProducts(html){const el=htmlDoc(html).querySelector('#catalog-data');if(!el)throw Error('Не найден каталог товаров');const a=JSON.parse(el.textContent);if(!Array.isArray(a)||!a.length)throw Error('Каталог пуст');return a;}
function serialize(doc){return '<!doctype html>\n'+doc.documentElement.outerHTML+'\n';}
function buildFiles(snapshot,changes){if(!changes.length)throw Error('Не выбраны изменения');const files=snapshot.files,old=readProducts(files['catalog/index.html']),next=E.updateProducts(old,changes),byId=new Map(next.map(p=>[p.id,p])),selected=new Set(changes.map(x=>x.id)),groups=new Set(next.filter(p=>selected.has(p.id)&&p.groupKey).map(p=>p.groupKey));const output={};
const cat=htmlDoc(files['catalog/index.html']);cat.querySelector('#catalog-data').textContent=JSON.stringify(next);
for(const c of cat.querySelectorAll('.catalog-item')){const group=c.dataset.id;const variants=next.filter(p=>(p.groupKey||p.id)===group);if(!variants.length)throw Error('Не найден товар карточки '+group);if(!variants.some(p=>selected.has(p.id)))continue;const p=variants.reduce((a,b)=>a.price<=b.price?a:b);const price=c.querySelector('.catalog-item-bottom strong');if(!price)throw Error('Не найдена цена карточки');price.textContent=(p.groupKey?'от ':'')+E.money(p.price);const a=c.querySelector('.catalog-buy');if(a)a.setAttribute('href',p.groupKey?p.page+'?variant='+encodeURIComponent(p.id):p.url);const imageLink=c.querySelector('a.model-photo');if(imageLink&&p.groupKey)imageLink.setAttribute('href',p.page+'?variant='+encodeURIComponent(p.id));}
output['catalog/index.html']=serialize(cat);
for(const group of groups){if(!/^[a-z0-9][a-z0-9-]*$/.test(group))throw Error('Неизвестная страница модели');const path=group+'/index.html';if(!files[path])throw Error('Страница модели не загружена: '+group);const doc=htmlDoc(files[path]),node=doc.querySelector('#product-data');if(!node)throw Error('Нет данных модели '+group);const data=JSON.parse(node.textContent);for(const id of selected){const p=byId.get(id);if(p.groupKey===group&&!data.variants.some(v=>v.id===id))throw Error('Вариант отсутствует на странице модели');}
data.variants=data.variants.map(v=>{if(!selected.has(v.id))return v;const p=byId.get(v.id);return {...v,price:p.price,url:E.orderUrl(v,p.price)};});node.textContent=JSON.stringify(data);doc.querySelector('#price').textContent='от '+E.money(Math.min(...data.variants.map(v=>v.price)));output[path]=serialize(doc);}
const home=htmlDoc(files['index.html']);let homeChanged=false;for(const card of home.querySelectorAll('.product-card')){const name=card.querySelector('h3')?.textContent.trim(),variants=next.filter(p=>p.model===name);if(!variants.some(p=>selected.has(p.id)))continue;const node=card.querySelector('.price-row strong');if(node){node.textContent='от '+E.money(Math.min(...variants.map(p=>p.price)));homeChanged=true;}}if(homeChanged)output['index.html']=serialize(home);
const xml=new DOMParser().parseFromString(files['yml.xml'],'application/xml');if(xml.querySelector('parsererror'))throw Error('Не удалось прочитать прайс для поисковиков');const named=new Map(old.filter(p=>selected.has(p.id)).map(p=>[p.name,byId.get(p.id)])),found=new Set();for(const offer of xml.querySelectorAll('offer')){const name=offer.querySelector('name')?.textContent,p=named.get(name);if(!p)continue;const price=offer.querySelector('price');if(!price)throw Error('Нет цены в выгрузке');price.textContent=String(p.price);found.add(p.id);}if(found.size!==changes.length)throw Error('Часть товаров не найдена в выгрузке. Обновление остановлено.');xml.documentElement.setAttribute('date',new Date().toISOString().slice(0,16).replace('T',' '));output['yml.xml']=new XMLSerializer().serializeToString(xml);
return output;}
class GitHub{
constructor(token){this.token=token||'';}
async request(path,method='GET',body){const r=await fetch('https://api.github.com/repos/'+REPO+'/'+path,{method,credentials:'omit',cache:'no-store',headers:{Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28',...(this.token?{Authorization:'Bearer '+this.token}:{}),...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});if(!r.ok){const messages={401:'Ключ недействителен или истёк.',403:'Недостаточно прав либо превышен лимит GitHub.',404:'Репозиторий или файл недоступен.',409:'Сайт уже изменился. Проверьте прайс заново.',422:'GitHub отклонил запись. Проверьте прайс заново; при повторе проверьте права ключа.'};throw Error(messages[r.status]||'Ошибка GitHub '+r.status+'. Попробуйте позже.');}return r.json();}
async head(){return (await this.request('git/ref/heads/main')).object.sha;}
async file(path,sha){if(!/^(index\.html|yml\.xml|catalog\/index\.html|[a-z0-9][a-z0-9-]*\/index\.html)$/.test(path))throw Error('Недопустимый путь');const d=await this.request('contents/'+path+'?ref='+sha);if(d.encoding!=='base64'||!d.content)throw Error('Не удалось прочитать файл '+path);return new TextDecoder().decode(Uint8Array.from(atob(d.content.replace(/\s/g,'')),c=>c.charCodeAt(0)));}
async snapshot(){const sha=await this.head(),commit=await this.request('git/commits/'+sha),catalog=await this.file('catalog/index.html',sha),products=readProducts(catalog);const paths=['index.html','yml.xml',...new Set(products.filter(p=>p.groupKey).map(p=>p.groupKey+'/index.html'))];const results=await Promise.all(paths.map(async p=>[p,await this.file(p,sha)]));return {sha,tree:commit.tree.sha,files:{'catalog/index.html':catalog,...Object.fromEntries(results)},products};}
async publish(snapshot,files){if(!this.token)throw Error('Введите ключ доступа для публикации');if(await this.head()!==snapshot.sha)throw Error('Сайт изменился после проверки. Загрузите прайс заново.');const entries=Object.entries(files).map(([path,content])=>{if(!/^(index\.html|yml\.xml|catalog\/index\.html|[a-z0-9][a-z0-9-]*\/index\.html)$/.test(path))throw Error('Недопустимый файл');return {path,content,mode:'100644',type:'blob'};});const tree=await this.request('git/trees','POST',{base_tree:snapshot.tree,tree:entries}),commit=await this.request('git/commits','POST',{message:'Update reviewed retail prices from owner price editor',tree:tree.sha,parents:[snapshot.sha]});try{await this.request('git/refs/heads/main','PATCH',{sha:commit.sha,force:false});}catch(error){let head;try{head=await this.head();}catch{}if(head!==commit.sha)throw error;}return {sha:commit.sha};}
}
return {readProducts,buildFiles,GitHub};
});
