const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {DOMParser}=require(process.env.PRICE_TEST_DOM||'linkedom');global.DOMParser=DOMParser;global.XMLSerializer=class{serializeToString(doc){return doc.toString()}};
const E=require('../admin/prices/engine'),P=require('../admin/prices/publisher'),root=path.join(__dirname,'..');const files={};for(const p of ['catalog/index.html','index.html','yml.xml',...fs.readdirSync(root).filter(x=>/^iphone-/.test(x)).map(x=>x+'/index.html')])files[p]=fs.readFileSync(path.join(root,p),'utf8');const products=P.readProducts(files['catalog/index.html']);const snapshot={sha:'old-head',tree:'base-tree',files,products};
const full=products.map(p=>p.name.replace(/^iPhone /,'').replace(/^Apple Watch Series 11/,'S11').replace(/^Apple Watch SE /,'SE')+' - '+(p.price-1990).toLocaleString('ru-RU')).join('\n');let preview=E.preview(full,products,{markup:1990,preorderMarkup:4990,includePreorders:false});assert.equal(preview.rows.filter(x=>x.status==='same').length,125);assert.equal(preview.rows.filter(x=>x.status==='protected').length,16);assert.equal(preview.issues.length,0);
const sample='iCenter Stavropol, [17 сен. 2026 в 19:40]\n▪️ Apple\nAirPods 4 - 10.500\nОт 10 шт - 1.650\n17 Pro 256GB Blue 🇯🇵 - 98.500 🚛\n18 pro 256 black esim 135000 18 pro 256 burgundy 1sim 143000🔥❗️';preview=E.preview(sample,products,{markup:1990,preorderMarkup:4990,includePreorders:false});assert.equal(preview.rows.find(x=>x.id==='new0').price,12490);assert.equal(preview.rows.filter(x=>x.status==='protected').length,2);assert.equal(preview.ignored.length,3);assert.equal(preview.issues.length,0);
preview=E.preview('18 pro 256 black esim 135000',products,{markup:1990,preorderMarkup:4990,includePreorders:true});assert.equal(preview.rows[0].price,139990);
assert.equal(E.preview('17 Pro 256GB Blue - 98500',products,{markup:1990}).rows[0].status,'error');assert.equal(E.parse('18 pro 256 blue esim 135-00').issues.length,1);assert.equal(E.preview('AirPods 4 - 10000\nAirPods 4 - 11000',products,{markup:1990}).rows.filter(x=>x.status==='error').length,2);assert.throws(()=>E.preview('AirPods 4 - 10000',products,{markup:-1}));assert.equal(E.key('17 Pro Max 1 TB Silver 🇯🇵'),E.key('iPhone 17 Pro Max 1TB Silver 🇯🇵'));assert.notEqual(E.key('17 Pro 256 Blue 🇯🇵'),E.key('17 Pro 256 Blue 🇪🇺'));
const changes=products.filter(p=>['new0','new91','pre0'].includes(p.id)).map(p=>({id:p.id,oldPrice:p.price,price:p.price+1234}));assert.equal(changes.length,3);const result=P.buildFiles(snapshot,changes),next=P.readProducts(result['catalog/index.html']);for(const p of products){const n=next.find(x=>x.id===p.id),change=changes.find(x=>x.id===p.id);if(!change)assert.deepEqual(n,p);else{assert.equal(n.price,change.price);if(p.url.startsWith('https://wa.me/'))assert(new URL(n.url).searchParams.get('text').includes(E.money(change.price)));}}
for(const [p,c] of Object.entries(result).filter(([p])=>p.startsWith('iphone-'))){const doc=new DOMParser().parseFromString(c,'text/html'),data=JSON.parse(doc.querySelector('#product-data').textContent);for(const x of changes)if(data.variants.some(v=>v.id===x.id))assert.equal(data.variants.find(v=>v.id===x.id).price,x.price);assert(doc.querySelector('.iphone-assurances'));}
const xml=new DOMParser().parseFromString(result['yml.xml'],'application/xml');for(const x of changes){const name=products.find(p=>p.id===x.id).name;const offer=[...xml.querySelectorAll('offer')].find(o=>o.querySelector('name').textContent===name);assert.equal(Number(offer.querySelector('price').textContent),x.price);}
const allChanges=products.map(p=>({id:p.id,oldPrice:p.price,price:p.price+1}));const allFiles=P.buildFiles(snapshot,allChanges);assert.equal(P.readProducts(allFiles['catalog/index.html']).filter(p=>p.price===products.find(x=>x.id===p.id).price+1).length,141);assert.equal(Object.keys(allFiles).filter(p=>p.startsWith('iphone-')).length,10);assert.throws(()=>P.buildFiles(snapshot,[{id:'missing',oldPrice:1,price:10}]));assert.throws(()=>P.buildFiles(snapshot,[{id:'new0',oldPrice:1,price:10}]));
(async()=>{const api=new P.GitHub('test-key'),calls=[];api.request=async(p,method='GET',body)=>{calls.push({p,method,body});if(p==='git/ref/heads/main')return {object:{sha:'old-head'}};if(p==='git/trees')return {sha:'tree'};if(p==='git/commits')return {sha:'commit'};if(p==='git/refs/heads/main')return {};throw Error(p)};await api.publish(snapshot,result);assert.equal(calls.at(-1).body.force,false);assert.equal(calls.at(-2).body.parents[0],'old-head');assert(!JSON.stringify(calls).includes('supplierPrice'));api.head=async()=> 'new-head';const before=calls.length;await assert.rejects(api.publish(snapshot,result),/Сайт изменился/);assert.equal(calls.length,before);assert(!fs.readFileSync(path.join(root,'admin/prices/editor.js'),'utf8').includes('localStorage'));console.log('PASS: 141 variant matches, protected preorders, malformed/duplicate/ambiguous rows, all price surfaces and order URLs, atomic publication, conflict protection, no token storage.');})().catch(e=>{console.error(e);process.exitCode=1});
